// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ringsaturn/tzf-server/internal/app"
	"github.com/ringsaturn/tzf-server/internal/config"
	"github.com/ringsaturn/tzf-server/internal/finder"
	"github.com/ringsaturn/tzf-server/internal/httpserver"
	"github.com/ringsaturn/tzf-server/internal/redisserver"
	"github.com/ringsaturn/tzf-server/internal/wraps"
)

import (
	_ "embed"
)

// Injectors from wire.go:

func initService(ctx context.Context) (*app.App, error) {
	configConfig := config.NewConfigFromArgs()
	tZfinder, err := finder.NewFinder(configConfig)
	if err != nil {
		return nil, err
	}
	tzfServiceHTTPServer := wraps.NewTZFServiceServer(tZfinder)
	hertz := httpserver.NewServer(configConfig, tzfServiceHTTPServer)
	server := redisserver.NewServer(tZfinder)
	appApp := app.NewApp(hertz, server)
	return appApp, nil
}
