name: build

on:
  push:
    branches: [main]
    tags:
      - "*"    
  pull_request:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read
    env:
      IMAGE_REGISTRY: "docker.io"
      IMAGE_OWNER: "ringsaturn"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate short SHA
        uses: benjlevesque/short-sha@v3.0
        id: gen-short-sha

      - name: Generate image info
        id: gen-image-info
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            echo "::set-output name=image_name::${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ github.event.repository.name }}"
            echo "::set-output name=image_tag::${{ github.ref }}"
          else
            echo "::set-output name=image_name::${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ github.event.repository.name }}"
            echo "::set-output name=image_tag::$(echo ${{ github.ref_name }}-${{ steps.gen-short-sha.outputs.sha }} | tr '/' '-')"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: "ringsaturn"
          password: "${{ secrets.CI_TOKEN}}"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.gen-image-info.outputs.image_name }}:${{ steps.gen-image-info.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
