name: build

on:
  release:
    types: [created]

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read
    env:
      IMAGE_REGISTRY: "ghcr.io"
      IMAGE_OWNER: "ringsaturn"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate short SHA
        uses: benjlevesque/short-sha@v1.2
        id: gen-short-sha

      - name: Generate image info
        id: gen-image-info
        run: |
          echo "::set-output name=image_name::${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ github.event.repository.name }}"
          echo "::set-output name=image_tag::$(echo ${{ github.ref_name }}-${{ steps.gen-short-sha.outputs.sha }} | tr '/' '-')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: "ringsaturn"
          password: "${{ secrets.CI_TOKEN}}"

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          # push: ${{ github.event_name == 'release' }}
          push: true
          tags: ${{ steps.gen-image-info.outputs.image_name }}:${{ steps.gen-image-info.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
