name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buf:
    name: buf
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "latest"
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"

  golangci:
    name: golangci-lint
    needs: [buf]
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

  test:
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: make install
      - run: make build
      - run: make test
      - run: make bench

      - name: Build Coverage Report
        run: |
          make cover
          mkdir coverage-report
          mv coverage.html ./coverage-report/
          ls -alh coverage-report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: "Coverage Report"
          path: "./coverage-report"
          retention-days: 3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
