name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci:
    name: golangci-lint
    strategy:
      matrix:
        go: ["1.21"]
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - run: go install github.com/mfridman/tparse@latest

      - run: make build
      - run: make test
      - run: make bench

      - name: Build Coverage Report
        run: |
          make cover
          mkdir coverage-report
          mv coverage.html ./coverage-report/
          ls -alh coverage-report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: "Coverage Report"
          path: "./coverage-report"
          retention-days: 3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
