name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buf:
    name: buf
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          pr_comment: true
          breaking: flase
          # breaking_against: "https://github.com/ringsaturn/tzf.git#branch=main"
          push: ${{ github.ref == 'refs/heads/main' }}

  golangci:
    name: golangci-lint
    needs: [buf]
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

  test:
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: make install
      - run: make build
      - run: make test
      - run: make bench

      - name: Build Coverage Report
        run: |
          make cover
          mkdir coverage-report
          mv coverage.html ./coverage-report/
          ls -alh coverage-report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: "Coverage Report"
          path: "./coverage-report"
          retention-days: 3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
